export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{backgroundColor:"lightblue",padding:"1rem"}}>
          <p>This is a header</p>
        </header>
        {children}
        <footer style={{backgroundColor:"ghostwhite",padding:"1rem"}}>
          <p>This is a footer</p>
        </footer>
        </body>
    </html>
  )
}
